# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "core.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  {{- if not .Values.loki.enabled }}
  - pods/log
  {{- end }}
  verbs:
  - get
  - list
{{- if not .Values.loki.enabled }}
- apiGroups:
  - "metrics.k8s.io"
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
{{- end }}
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  - configmaps
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - kubeai.org
  resources:
  - models
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - get
  - list
{{- if .Values.envoyGateway.enabled }}
{{- if .Values.envoyGateway.genericGateway.enabled }}
- apiGroups:
  - gateway.envoyproxy.io
  resources:
  - backends
  - envoyextensionpolicies
  verbs:
  - create
  - get
  - list
  - delete
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - get
  - list
  - delete
{{- end }}
{{- if .Values.envoyGateway.aiGateway.enabled }}
- apiGroups:
  - aigateway.envoyproxy.io
  resources:
  - aigatewayroutes
  - aiservicebackends
  verbs:
  - create
  - get
  - list
  - delete
{{- end }}
{{- end }}
