# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "core.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - "metrics.k8s.io"
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  - configmaps
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - kubeai.org
  resources:
  - models
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - get
  - list
