apiVersion: v2
name: digitalhub
description: A Helm chart for Kubernetes
type: application
version: 0.2.10
appVersion: "0.1.0"
dependencies:
- name: docker-registry
  version: "2.2.2"
  repository: "https://helm.twun.io"
  condition: docker-registry.enabled
- name: mlrun-ce
  version: "0.6.3-rc3"
  condition: mlrun-ce.enabled
- name: coder
  version: "0.1.0"
  condition: coder.enabled
- name: postgres-operator
  version: "1.10.0"
  repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"
  condition: postgres-operator.enabled
- name: ext-postgres-operator
  version: "1.2.4"
  condition: ext-postgres-operator.enabled
- name: custom-resource-manager
  condition: custom-resource-manager.enabled
  version: "0.1.0"
- name: postgrest-operator
  condition: postgrest-operator.enabled
  version: "0.1.0"
- name: grafana
  repository: "https://grafana.github.io/helm-charts"
  condition: grafana.enabled
  version: "7.0.3"
- name: core
  condition: core.enabled