FROM maven:3.8-jdk-8 as build
#Dremio build
#NOTE: must be tested on AMD64 platform
WORKDIR /dremio
RUN git clone -b oauth2-single-tenant https://github.com/smartcommunitylab/dremio-oss.git
WORKDIR /dremio/dremio-oss
RUN mvn install -DskipTests=true -Dlicense.skip -ntp
RUN mkdir -p /opt/dremio && mv /dremio/dremio-oss/distribution/server/target/dremio*.tar.gz /opt/dremio/dremio.tar.gz
RUN tar vxfz /opt/dremio/dremio.tar.gz -C /opt/dremio --strip-components=1 && rm /opt/dremio/dremio.tar.gz

FROM openjdk:8-jdk as run
LABEL org.label-schema.name='dremio/dremio-oss'
LABEL org.label-schema.description='Dremio OSS.'

#Dremio setup
ARG USER=dremio
ARG USER_GROUP=dremio

RUN \
  mkdir -p /opt/dremio \
  && mkdir -p /var/lib/dremio \
  && mkdir -p /var/run/dremio \
  && mkdir -p /var/log/dremio \
  && mkdir -p /opt/dremio/data \
  && groupadd --system ${USER_GROUP} \
  && useradd --base-dir /var/lib/dremio --system --gid ${USER_GROUP} ${USER} \
  && chown -R dremio:dremio /opt/dremio/data \
  && chown -R dremio:dremio /var/run/dremio \
  && chown -R dremio:dremio /var/log/dremio \
  && chown -R dremio:dremio /var/lib/dremio

COPY --chown=dremio:dremio --from=build /opt/dremio /opt/dremio

EXPOSE 9047/tcp
EXPOSE 31010/tcp
EXPOSE 45678/tcp

USER dremio
WORKDIR /opt/dremio
ENV DREMIO_HOME /opt/dremio
ENV DREMIO_PID_DIR /var/run/dremio
ENV DREMIO_GC_LOGS_ENABLED="no"
ENV DREMIO_LOG_DIR="/var/log/dremio"
ENV SERVER_GC_OPTS="-XX:+PrintGCDetails -XX:+PrintGCDateStamps"
#ENTRYPOINT ["bin/dremio", "start-fg"]