FROM quay.io/mlrun/jupyter:1.4.0

LABEL org.opencontainers.image.source=https://github.com/scc-digitalhub/digitalhub

# Create conda env for digitalhub-core kernel
RUN conda create -n digitalhub-core python=3.9 --no-default-packages

# Clone digitalhub-core repo
RUN git clone https://github.com/scc-digitalhub/digitalhub-sdk.git

# Install remote-only dependencies in base kernel
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]
RUN pip install digitalhub-sdk/core
RUN pip install digitalhub-sdk/data/modules/dbt
RUN pip install digitalhub-sdk/data/modules/nefertem

# Install full dependencies in digitalhub-core kernel
SHELL ["conda", "run", "-n", "digitalhub-core", "/bin/bash", "-c"]
RUN python -m pip install ipykernel
RUN python -m ipykernel install --name digitalhub-core --display-name "digitalhub-core" --user

# Install digitalhub-core, dbt, neferetem and nefertem plugins
RUN pip install digitalhub-sdk/core
RUN pip install digitalhub-sdk/data/modules/dbt[local]
RUN pip install digitalhub-sdk/data/modules/nefertem[local]
RUN git clone https://github.com/scc-digitalhub/nefertem.git
RUN pip3 install ./nefertem/plugins/frictionless*
RUN pip3 install ./nefertem/plugins/duckdb*
RUN pip3 install ./nefertem/plugins/sqlalchemy*
RUN pip3 install ./nefertem/plugins/ydata*

# Cleanup
RUN rm -rf digitalhub-core nefertem