global:
  cleanup:
    persistentVolumeClaim: false
    ingress: false
  service:
    type: &serviceType "ClusterIP"
  registry:
    url: registry.${DOMAIN}
    username: "digitalhub-test"
    password: "digitalhub-test"
    email: "admin@${DOMAIN}"
    secretName: "registry-credentials"
  basicAuth:
    enabled: false
    username: "digitalhub-test"
    password: "digitalhub-test"
    secretName: "basic-auth"
  nuclio:
    dashboard:
      nodePort: ""
  externalHostAddress: &globalExternalUrl ""

docker-registry: 
  enabled: true
  fullnameOverride: digitalhub-docker-registry
  className: nginx
  service:
    type: *serviceType
    nodePort: ""
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Registry realm'
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    path: /
    hosts:
      - registry.${DOMAIN}
    tls:
      - secretName: digitalhub-test-wildcard
        hosts: 
          - registry.${DOMAIN}
  persistence:
    accessMode: 'ReadWriteOnce'
    enabled: true
    size: 128Gi
  updateStrategy:
    type: Recreate

mlrun-ce: 
  enabled: true
  nuclio:
    fullnameOverride: nuclio
    controller:
      enabled: true
    dashboard:
      enabled: true
      containerBuilderKind: kaniko
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
          nginx.ingress.kubernetes.io/auth-realm: 'Registry realm'
        hosts: 
          - nuclio.${DOMAIN}
        tls:
          - secretName: digitalhub-test-wildcard
            hosts:
              - nuclio.${DOMAIN}
    rbac:
      create: true
      crdAccessMode: namespaced
    crd:
      create: true
    platform:
      ingressConfig:
        tlsSecret: "digitalhub-test-wildcard"
      logger:
        sinks:
          myStdoutLoggerSink:
            kind: stdout
            attributes:
              encoding: console
              timeFieldName: time
              timeFieldEncoding: iso8601
        system:
        - level: debug
          sink: myStdoutLoggerSink
        functions:
        - level: debug
          sink: myStdoutLoggerSink
  mlrun:
    storage: filesystem
    fullnameOverride: mlrun
    nuclio:
      mode: enabled
      uiURL: "https://nuclio.${DOMAIN}/"
    rbac:
      create: true
    v3io:
      enabled: false
    api:
      fullnameOverride: mlrun-api
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: mlrun-api.${DOMAIN}
            paths: 
              - pathType: ImplementationSpecific
                path: /
        tls:
          - secretName: digitalhub-test-wildcard
            hosts:
              - mlrun-api.${DOMAIN}
      volumes:
        storageOverride:
          persistentVolumeClaim:
            claimName: mlrun-api-pvc
      persistence:
        enabled: true
        existingClaim:
        storageClass:
        accessMode: "ReadWriteOnce"
        size: "8Gi"
        # annotations:
        #   helm.sh/resource-policy: "keep"
      envFrom:
        - configMapRef:
            name: mlrun-common-env
        - configMapRef:
            name: mlrun-pipelines-config
            optional: true
        - configMapRef:
            name: mlrun-spark-config
            optional: true
        - configMapRef:
            name: mlrun-override-env
            optional: true
      extraPersistentVolumeMounts: ~
    ui:
      fullnameOverride: mlrun-ui
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations: 
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
          nginx.ingress.kubernetes.io/auth-realm: 'Registry realm'
        hosts:
          - host: mlrun.${DOMAIN}
            paths: 
              - pathType: ImplementationSpecific
                path: /
        tls:
          - secretName: digitalhub-test-wildcard
            hosts:
              - mlrun.${DOMAIN}
    db:
      name: db
      fullnameOverride: mlrun-db
      securityContext: 
        runAsUser: 999
      podSecurityContext:
        runAsUser: 999
        fsGroup: 999    
      volumes:
        storageOverride:
          persistentVolumeClaim:
            claimName: mlrun-db-pvc
      persistence:
        enabled: true
        existingClaim:
        storageClass:
        accessMode: "ReadWriteOnce"
        size: "8Gi"
        # annotations:
        #   helm.sh/resource-policy: "keep"
    httpDB:
      dbType: mysql
      dirPath: "/mlrun/db"
      dsn: mysql+pymysql://root@mlrun-db:3306/mlrun
      oldDsn: sqlite:////mlrun/db/mlrun.db?check_same_thread=false
    ce:
      mode: full
  jupyterNotebook:
    enabled: false
    persistence:
      enabled: false
  mpi-operator:
    fullnameOverride: mpi-operator
    crd:
      create: true
    rbac:
      clusterResources:
        create: true
      namespaced:
        create: true
    deployment:
      create: true
  minio:
    enabled: true
    rootUser: minio
    rootPassword: ${MINIO_PASSWORD}
    mode: standalone
    replicas: 1
    resources:
      requests:
        memory: 0.5Gi
    service:
      type: ClusterIP
    consoleService:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: "nginx"
      path: /
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      hosts:
        - minio-api.${DOMAIN}
      tls:
        - secretName: digitalhub-test-wildcard
          hosts:
            - minio-api.${DOMAIN}
    consoleIngress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      path: /
      hosts:
        - minio.${DOMAIN}
      tls:
        - secretName: digitalhub-test-wildcard
          hosts:
            - minio.${DOMAIN}
    persistence:
      enabled: true
      size: 128Gi
    fullnameOverride: minio
    buckets:
      - name: mlrun
        policy: none
        purge: false
  spark-operator:
    enabled: true
    fullnameOverride: spark-operator
    webhook:
      enable: true
    serviceAccounts:
      spark:
        name: "sparkapp"
  pipelines:
    enabled: true
    name: pipelines
    persistence:
      enabled: true
      existingClaim:
      storageClass:
      accessMode: "ReadWriteOnce"
      size: "128Gi"
      # annotations:
      #   helm.sh/resource-policy: "keep"
    db:
      username: root
    ui:
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
          nginx.ingress.kubernetes.io/auth-realm: 'Registry realm'
        hosts:
          - host: kubeflow-ui.${DOMAIN}
            paths: 
              - pathType: ImplementationSpecific
                path: /
        tls:
        - secretName: digitalhub-test-wildcard
          hosts:
            - kubeflow-ui.${DOMAIN}
    minio:
      enabled: true
      accessKey: "minio"
      secretKey: "${MINIO_PASSWORD}"
      endpoint: "minio"
      endpointPort: "9000"
      bucket: "mlrun"
  kube-prometheus-stack:
    enabled: false

coder: 
  enabled: true
  externalHostAddress: coder.${DOMAIN}
  username: test
  password: ${MINIO_PASSWORD}
  email: test@digitalhub.test
  template:
    customTemplates:
      - name: jupyter
        nodePort: "30040"
        iconUrl: https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png
      - name: dremio
        nodePort: "30120"
        iconUrl: https://cdn.icon-icons.com/icons2/2699/PNG/512/dremio_logo_icon_168234.png
      - name: sqlpad
        nodePort: "30140"
        iconUrl: https://i.ibb.co/TrBDsZM/sqlpad.png
      - name: grafana
        nodePort: "30130"
        iconUrl: https://cdn.icon-icons.com/icons2/2699/PNG/512/grafana_logo_icon_171048.png
      - name: dashboard
        nodePort: "30110"
        iconUrl: https://svgshare.com/i/u5R.svg
  coder:
    image:
      tag: v2.1.5
    ingress:
      enable: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      host: coder.${DOMAIN}
      wildcardHost: "*.coder.${DOMAIN}"
      tls:
        enable: true
        secretName: digitalhub-test-wildcard
        wildcardSecretName: digitalhub-test-wildcard

    service:
      type: *serviceType
      httpNodePort: ""

postgres-operator: 
  enabled: true

ext-postgres-operator:
  enabled: true
  postgres:
    host: database-postgres-cluster
    user: ""
    password: ""
    uri_args: " "
    cloud_provider: " "
    default_database: "postgres"
  postgresCredsExistingSecrets:
    username:
      secretName: "digitalhub-owner-user.database-postgres-cluster.credentials.postgresql.acid.zalan.do" 
      secretKey: "username"
    password:
      secretName: "digitalhub-owner-user.database-postgres-cluster.credentials.postgresql.acid.zalan.do" 
      secretKey: "password"

kubernetes-resource-manager:
  enabled: true
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Registry realm'
    hosts:
      - host: crm.${DOMAIN}
        paths: 
          - pathType: ImplementationSpecific
            path: /
    tls:
    - secretName: digitalhub-test-wildcard
      hosts:
        - crm.${DOMAIN}
