apiVersion: v2
name: resources-profile-generator
description: Helm chart to generate resource profile templates in a ConfigMap
type: application
version: 0.2.0
appVersion: "1.0.0"
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
