FROM sqlpad/sqlpad:7.5.3

LABEL org.opencontainers.image.source=https://github.com/scc-digitalhub/digitalhub

RUN groupadd -f appuser \
    && useradd -m -s /bin/bash -g appuser appuser \
    && chown -R appuser:appuser /home/appuser \
    && chown -R appuser:appuser /usr/app

WORKDIR /home/appuser/app

RUN mkdir -p /var/lib/sqlpad && chown -R appuser:appuser /var/lib/sqlpad

USER appuser
