FROM timescale/timescaledb:2.20.0-pg16 AS timescale

FROM ghcr.io/cloudnative-pg/postgresql:16

LABEL org.opencontainers.image.source=https://github.com/scc-digitalhub/digitalhub

USER root

RUN apt-get update && apt-get install -y curl gnupg ca-certificates lsb-release \
 && curl -sSL https://packagecloud.io/timescale/timescaledb/gpgkey | gpg --dearmor -o /etc/apt/trusted.gpg.d/timescale.gpg \
 && echo "deb https://packagecloud.io/timescale/timescaledb/debian/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/timescaledb.list \
 && apt-get update

RUN echo "shared_preload_libraries = 'timescaledb'" >> /usr/share/postgresql/postgresql.conf.sample

COPY --from=timescale /docker-entrypoint-initdb.d/* /docker-entrypoint-initdb.d/
COPY --from=timescale /usr/local/bin/timescaledb-tune /usr/local/bin/timescaledb-tune
RUN chmod a+r /docker-entrypoint-initdb.d/*

RUN apt-get update && apt-get install -y \
    postgresql-16-postgis-3 \
    timescaledb-2-postgresql-16 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
USER 26
