FROM nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04
RUN apt-get update && \
    apt-get install -y ffmpeg software-properties-common git
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3 python3-distutils-extra && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY --from=ghcr.io/astral-sh/uv:0.4.11 /uv /bin/uv
RUN groupadd -g 65500 whisper && \
    useradd -m -u 65500 -g whisper whisper
USER 65500
WORKDIR /home/whisper/faster-whisper-server
RUN git clone --branch v0.5.0 https://github.com/speaches-ai/speaches.git .
# https://docs.astral.sh/uv/guides/integration/docker/#intermediate-layers
RUN uv sync --frozen --extra ui
ENV WHISPER__MODEL=Systran/faster-whisper-large-v3
ENV WHISPER__INFERENCE_DEVICE=auto
ENV UVICORN_HOST=0.0.0.0
ENV UVICORN_PORT=8000
CMD ["uv", "run", "uvicorn", "--factory", "faster_whisper_server.main:create_app"]
