# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if and .Values.coder.enabled (or .Values.coder.template.upgrade.enabled .Values.coder.workspace.upgrade.enabled) (or .Values.coder.template.upgrade.token .Values.coder.existingSecrets.adminSessionTokenExistingSecret.secretName) (eq (include "digitalhub.coderTemplatesUpgradeRequired" .) "true") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: coder-template-upgrade-state
  labels:
    {{- include "digitalhub.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
    checksum/coder-templates: {{ include "digitalhub.coderTemplatesChecksum" . }}
{{- end }}
