apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: loki-stack
spec:
  clusterSelector:
    matchLabels:
      app: digitalhub
      env: test
      monitoring: enabled
  repoURL: https://grafana.github.io/helm-charts
  chartName: loki-stack
  namespace: monitoring
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: false
  valuesTemplate: |
    loki:
      enabled: true
      isDefault: false
      config:
        table_manager:
          retention_deletes_enabled: true
          retention_period: 672h
      persistence:
        enabled: true
        accessModes:
        - ReadWriteOnce
        size: 128Gi
        annotations: {}
        subPath: "loki"
        storageClassName: 
      serviceMonitor:
        enabled: true
        interval: ""
        additionalLabels: {}
        annotations: {}
        # scrapeTimeout: 10s
    promtail:
      enabled: true
      serviceMonitor:
        enabled: true
        namespaceSelector: {}
        annotations: {}
        labels: {}
        interval: null
        scrapeTimeout: null
    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
