{{ if .Values.jupyterNotebook.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyter-common-env
data:
  S3_ENDPOINT_URL: {{ include "mlrun-ce.minio.service.url" . }}
  AWS_SECRET_ACCESS_KEY: {{ include "mlrun-ce.minio.tenantPassword" . }}
  AWS_ACCESS_KEY_ID: {{ include "mlrun-ce.minio.tenantUser" . }}
{{- end}}
