{{ if .Values.mlrun.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlrun-common-env
data:
  MLRUN_STORAGE__AUTO_MOUNT_TYPE: s3
  MLRUN_STORAGE__AUTO_MOUNT_PARAMS: "aws_access_key={{ include "mlrun-ce.minio.tenantUser" . }},aws_secret_key={{ include "mlrun-ce.minio.tenantPassword" . }},endpoint_url={{ include "mlrun-ce.minio.service.url" . }}"
  MLRUN_HTTPDB__PROJECTS__FOLLOWERS: nuclio
  S3_ENDPOINT_URL: {{ include "mlrun-ce.minio.service.url" . }}
  AWS_SECRET_ACCESS_KEY: {{ include "mlrun-ce.minio.tenantPassword" . }}
  AWS_ACCESS_KEY_ID: {{ include "mlrun-ce.minio.tenantUser" . }}
  MLRUN_HTTPDB__REAL_PATH: s3://
  MLRUN_ARTIFACT_PATH: s3://{{ include "mlrun-ce.minio.bucket" . }}/projects/{{ `{{run.project}}` }}/artifacts
  MLRUN_FEATURE_STORE__DATA_PREFIXES__DEFAULT: s3://{{ include "mlrun-ce.minio.bucket" . }}/projects/{project}/FeatureStore/{name}/{kind}
  MLRUN_FEATURE_STORE__DATA_PREFIXES__NOSQL: ""
  MLRUN_CE__MODE: {{ .Values.mlrun.ce.mode }}
  MLRUN_CE__VERSION: {{ .Chart.Version }}
  MLRUN_DEFAULT_TENSORBOARD_LOGS_PATH: /home/jovyan/data/tensorboard/{{ `{{project}} `}}
  MLRUN_FEATURE_STORE__DEFAULT_TARGETS: parquet
  MLRUN_MODEL_ENDPOINT_MONITORING__STORE_TYPE: sql
{{- if (and .Values.mlrun.modelMonitoring.secretDsn .Values.mlrun.modelMonitoring.secretDsn.name) }}
  MLRUN_MODEL_ENDPOINT_MONITORING__ENDPOINT_STORE_CONNECTION: "{{ template "mlrun-ce.mlrun.modelMonitoring.DSN" . }}"
{{- end }}
  MLRUN_GRAFANA_URL: http://{{ .Values.global.externalHostAddress }}:{{ index .Values "kube-prometheus-stack" "grafana" "service" "nodePort" }}
{{- end}}
